### ISSUE TITLE
Wrap neurom calls in try/except in examples

### ISSUE THREAD

**Issue by SBottani** [SENeC-Initiative/DeNSE#25]
Hi,
Install scripts pip install  `pyneuroml`.

Examples with` import neurom `where not working.
I had to `pip install --user neurom` instead to have it work

Should install script be updated ?

Best

**Comment by Silmathoron** [comment]
No, ``pyneuroml`` is used to export neurons to the standard NML format (we need it in ``io``), while ``neurom`` is just to show users that they can use other tools to analyze the morphologies.
What we should have, however, is a ``try: except`` in the examples including ``neurom`` so that they run even if users do not have it installed.
Could you do that when you clean up the examples?

**Comment by tfardet** [comment]
Fixed by #45
